name: Gen and update plists

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download IPAs from current release
        uses: robinraju/release-downloader@v1.9.0
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: "*.ipa"
          out-file-path: ipa-assets

      - name: Get info and build plists
        run: |
          mkdir -p plists
          for ipa in ipa-assets/*.ipa; do
            echo "Processing $ipa"
            tmp=$(mktemp -d)
            unzip -p "$ipa" 'Payload/*.app/Info.plist' > "$tmp/Info.plist"

            BUNDLE_ID=$(plutil -extract CFBundleIdentifier xml1 -o - "$tmp/Info.plist" | xmllint --xpath 'string(//string)' -)
            VERSION=$(plutil -extract CFBundleShortVersionString xml1 -o - "$tmp/Info.plist" | xmllint --xpath 'string(//string)' -)
            NAME=$(plutil -extract CFBundleDisplayName xml1 -o - "$tmp/Info.plist" | xmllint --xpath 'string(//string)' -)

            PLIST_PATH="plists/${BUNDLE_ID}_${VERSION}.plist"
            
            sed -e "s|ASSET_URL_PLACEHOLDER|${{ github.event.release.assets_url }}/$(basename "$ipa")|g" \
                -e "s|BUNDLE_ID_PLACEHOLDER|${BUNDLE_ID}|g" \
                -e "s|VERSION_PLACEHOLDER|${VERSION}|g" \
                -e "s|NAME_PLACEHOLDER|${NAME}|g" \
                template/body.plist > "$PLIST_PATH"
            
            echo "Successfully generated $PLIST_PATH"
          done

      - name: Commit & push generated plists
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plists/*.plist
          if git diff --cached --quiet; then
            echo "No new plists to commit."
          else
            git commit -m "chore: add OTA plists for ${{ github.event.release.tag_name }}"
            git push
          fi
