name: Gen and update plists

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download IPAs
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          tag: "0.0.1"
          fileName: "*.ipa"
          out-file-path: ipa-assets
          latest: false

      - name: Get info and build plists
        run: |
          mkdir -p plists
          for ipa in ipa-assets/*.ipa; do
            echo "Processing $ipa"
            tmp=$(mktemp -d)
            unzip -p "$ipa" 'Payload/*.app/Info.plist' > "$tmp/Info.plist"

            BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" "$tmp/Info.plist")
            VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$tmp/Info.plist")
            NAME=$(/usr/libexec/PlistBuddy -c "Print CFBundleDisplayName" "$tmp/Info.plist" 2>/dev/null || /usr/libexec/PlistBuddy -c "Print CFBundleName" "$tmp/Info.plist")

            IPA_FILENAME=$(basename "$ipa")
            DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/download/0.0.1/$IPA_FILENAME"
            SAFE_VERSION=$(echo "$VERSION" | sed 's/[^a-zA-Z0-9._-]/_/g')
            PLIST_PATH="plists/${BUNDLE_ID}_${SAFE_VERSION}.plist"

            sed -e "s|ASSET_URL_PLACEHOLDER|$DOWNLOAD_URL|g" \
                -e "s|BUNDLE_ID_PLACEHOLDER|${BUNDLE_ID}|g" \
                -e "s|VERSION_PLACEHOLDER|${VERSION}|g" \
                -e "s|NAME_PLACEHOLDER|${NAME}|g" \
                template/body.plist > "$PLIST_PATH"

            echo "Successfully generated $PLIST_PATH"
          done

      - name: Commit & push generated plists
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plists/*.plist
          if git diff --cached --quiet; then
            echo "No new plists to commit."
          else
            git commit -m "chore: add OTA plists for ${{ github.event.release.tag_name }}"
            git push
          fi
